### ISSUE TITLE
Grouping projects in a folder/ group

### ISSUE THREAD

**Issue by Rjdesh** [CATALOG-Historic-Records/orphaned-wells-ui#107]

**Comment by Rjdesh** [comment]
- State Agencies/ researchers would start a project to extract data with an intent to analyze wells for certain area or date or attributes for getting reports to plan and propose future work/ policies : So our UI should map this effort to a Project entity.

- Each Project could have multiple document types to be digitized and reviewed. 
- From technical standpoint - each document AI processor would be mapped to digitizing a particular type of document.
- From a user standpoint - its easier to review similar documents together - hence all documents of same type could belong to a group to be reviewed together in same flow.
- A project will hence have two tabs for 2 views
  - Document Group for digitization and user review flow.
  - A flat view of all project documents could be viewed without grouping, and filter + group by options can be offered to group them as per user preferences?

**Comment by dangunter** [comment]
```
Project
  |
  +-- Document Group
         |
        +--- Documents...
```

**Comment by MichaelPesce** [comment]
We've been calling the new object Document Groups, but the current hierarchy is Projects -> Records. Any opposition to calling it Record Groups instead of Document Groups?

**Comment by dangunter** [comment]
I am ok with this, perhaps we should also then make sure we use the word "document" only to refer to PDFs or paper documents, which may or may not become multiple records. In other words, records are digitized things that we can parse with a processor. Documents are the source of records, and the mapping will vary. Does that make sense?

**Comment by Rjdesh** [comment]
Yes, this separation makes sense!
So *documents* would be the collated PDFs we pass through splitter &
classifiers to output different types of well *records*.

**Comment by MichaelPesce** [comment]
I think this was mostly handled by #146

**Comment by MichaelPesce** [comment]
@Rjdesh can we call this completed?

**Comment by Rjdesh** [comment]
yup - this is completed.
