### ISSUE TITLE
Highlight attributes with low confidence for easy scanning

### ISSUE THREAD

**Issue by Rjdesh** [CATALOG-Historic-Records/orphaned-wells-ui#27]
- Low confidence attributes show red dot + red text for confidence value
- Updated attributes show blue dot next to confidence value + black text

![Image](https://github.com/CATALOG-Historic-Records/orphaned-wells-ui/assets/131914510/0ad73a63-0b7d-4185-977d-f8e227468409)

**Comment by MichaelPesce** [comment]
handled in #110
