### ISSUE TITLE
Fix ordering of attributes for ISGS documents

### ISSUE THREAD

**Issue by dangunter** [CATALOG-Historic-Records/orphaned-wells-ui#88]
Use ordering provided by ISGS, "hardcode" for now.

Consider adding to a hidden project settings record(s)

**Comment by Rjdesh** [comment]
sort order option :

![Image](https://github.com/CATALOG-Historic-Records/orphaned-wells-ui/assets/131914510/88258322-2a00-429d-992a-9941b035a317)

**Comment by dangunter** [comment]
So, perhaps we could call these "fields"? That seems to be a more common terminology. I might label the options:
* Schema order
* Form order // what Mike recently implemented, which is the same as "attributes detected" I think
* Confidence Low -> High
* Confidence High -> Low

**Comment by Rjdesh** [comment]
I used attributes detected - to convey that those not found will be at bottom - unlike schema order 🤔  
So its similar to form order but with only detected attributes. Not sure how to convey that.

**Comment by MichaelPesce** [comment]
repeat of #89? handled in #99, #100, #102
